# Generated by Django 3.1.5 on 2021-02-20 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 2, 20, 14, 52, 56, 45172)),
        ),
    ]
