# Generated by Django 3.1.5 on 2021-02-21 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210221_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 2, 21, 12, 49, 43, 34932)),
        ),
    ]
