# Generated by Django 3.1.5 on 2021-02-21 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210221_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 21, 14, 51, 55, 606285)),
        ),
    ]
