# Generated by Django 3.1.5 on 2021-02-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20210226_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed_user',
            new_name='following',
        ),
    ]
